project:
  type: website
  preview:
    port: 8080

execute: 
  freeze: auto

website:
  title: "Rembus"
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Home
      - julia.qmd
      - python.qmd
      - rust.qmd
    tools:
      - icon: github
        href: https://github.com/cardo-org/Rembus.jl
  page-footer: "Powered by [Quarto](https://quarto.org/) and the [Julia Programming Language](https://julialang.org/)."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
    grid:
      sidebar-width: 0px
css: styles.css



